### ISSUE TITLE
No tracking for other WiFi devices than learning device.

### ISSUE THREAD

**Issue by pawel-manu** [schollz/find-lf#12]
I am using public find-lf server.
When start my cluster and turn on "Track" mode,
I can only see single device tracked (the one used during "Learn" mode).
Dashboard and GET /location is showing just single smartphone device 
and shows only once I turn on Find-it app on that smartphone.

How to start tracking of all WiFi enabled devices?
Should I establish my private find-lf server to scan more devices?

**Comment by schollz** [comment]
It should already be scanning all devices.

Can you email me your group name? hypercubeplatforms@gmail.com

**Comment by pawel-manu** [comment]
Group name:
manutest

Dnia 17.06.2017 o godz. 15:07 Zack <notifications@github.com> napisał(a):

**Comment by schollz** [comment]
It looks like there are no fingerprints being received on the public lf.internalpositioning server for that group. Can you make sure that the Raspberry Pi's are transmitting?

**Comment by pawel-manu** [comment]
What am I doing wrong?
2 RPi's are turned on...
Fingerprints are only sent to group: manutest once I turn on mobile app... but not from RPi's ... they have route to lf.internalpositioning.com ...
Are there somewhere logs for that communication from RPi?

**Comment by schollz** [comment]
Yes. The pis should just be running `scan.py`. You can run that command yourself to see what happens. Also check is tshark is turned on `ps aux | grep tshark`

**Comment by pawel-manu** [comment]
It's issue with TL-WN722N in version 2 based on Realtek RTL8188EU (drivers for that not in the default distribution). Looking for solution, but not an issue with find-lf code :)
