### ISSUE TITLE
Role of WiFi adapter

### ISSUE THREAD

**Issue by ipozdnyakov** [schollz/find-lf#25]
In Readme.md

at the line

>> Do this for several Pis and then plug in the WiFi adapter that has "monitor" mode.

Could you please explain a bit on the role of this adapter in the system?

Thank you!

**Comment by ipozdnyakov** [comment]
Should I use one for each RPi or only one for the whole system?

**Comment by schollz** [comment]
Each Pi should have its own adapter. The adapter is used to scan for devices, and each Pi will be doing its own scanning in its own geographic region.

**Comment by ipozdnyakov** [comment]
Thank you very much!
